/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import java.awt.event.KeyEvent;
import javax.swing.JDialog;

/**
 *
 * @author cdani
 */
public class ConfirmacionPago extends javax.swing.JDialog {
    public int totalPagar;
    public boolean pagado = false;

    /**
     * Creates new form ConfirmacionPago
     */
    public ConfirmacionPago(JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        bEnviar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lTituloEncabezado = new javax.swing.JLabel();
        lCambio = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        cMetodoPago = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cRecibido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirmacion de pago");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(156, 195, 219));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTituloEncabezado.setFont(new java.awt.Font("Stencil", 0, 28)); // NOI18N
        lTituloEncabezado.setText("Confirmación de pago");
        jPanel2.add(lTituloEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 110));

        lCambio.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        lCambio.setText("Cambio:");
        jPanel1.add(lCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 340, -1));

        lTotal.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        lTotal.setText("Total");
        jPanel1.add(lTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, -1));

        cMetodoPago.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        cMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta" }));
        cMetodoPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cMetodoPagoItemStateChanged(evt);
            }
        });
        jPanel1.add(cMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, -1));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel3.setText("Metodo pago:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, -1));

        cRecibido.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        cRecibido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cRecibidoKeyReleased(evt);
            }
        });
        jPanel1.add(cRecibido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, -1));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel4.setText("Recibido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, -1));

        bEnviar.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        bEnviar.setText("Enviar");
        bEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(bEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cRecibidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cRecibidoKeyReleased
        char c = evt.getKeyChar();
    
        // Permitir solo dígitos (y la tecla de borrar)
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume(); // Ignorar la entrada no válida
        }   

        // Validar si el campo no está vacío antes de convertirlo a número
        if (cRecibido.getText().length() > 0) {
            try {
                int recibido = Integer.parseInt(cRecibido.getText());
                CalculaCambio(recibido);
            } catch (NumberFormatException e) {
                // Manejo de error si ocurre un problema al convertir
                System.out.println("Entrada no válida.");
            }
        }
    }//GEN-LAST:event_cRecibidoKeyReleased

    private void cMetodoPagoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cMetodoPagoItemStateChanged
        MostrarCampos();
    }//GEN-LAST:event_cMetodoPagoItemStateChanged

    private void bEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnviarActionPerformed
        pagado = true;
        dispose();
    }//GEN-LAST:event_bEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmacionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                ConfirmacionPago dialog = new ConfirmacionPago(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEnviar;
    private javax.swing.JComboBox<String> cMetodoPago;
    private javax.swing.JTextField cRecibido;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lCambio;
    private javax.swing.JLabel lTituloEncabezado;
    private javax.swing.JLabel lTotal;
    // End of variables declaration//GEN-END:variables
    
    public void setTotalPagar(int total){
        totalPagar = total;
        lTotal.setText("Total a pagar: $"+String.valueOf(totalPagar));
    }
    
    void CalculaCambio(int recibido){
        int total;
        if(recibido < totalPagar){
            lCambio.setText("Error: No puede ser menor al total");
            bEnviar.setEnabled(false);
        }else if(recibido >= totalPagar){
            total = recibido - totalPagar;
            lCambio.setText("Cambio: $"+total);
            bEnviar.setEnabled(true);
        }
    }
    
    void MostrarCampos(){
        if(cMetodoPago.getSelectedIndex() == 1){
            jLabel4.setVisible(false);
            cRecibido.setVisible(false);
            lCambio.setVisible(false);
            bEnviar.setEnabled(true);
        }else{
            jLabel4.setVisible(true);
            cRecibido.setVisible(true);
            lCambio.setVisible(true);
            CalculaCambio(Integer.parseInt(cRecibido.getText()));
            
        }
    }
}
