/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cdani
 */
public class RegistrarVentas extends javax.swing.JDialog {

    /**
     * Creates new form RegistrarVentas
     */
    public RegistrarVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        jCalendario.setVisible(false);
        lFechaRegistro.setText("Registrar en "+FechaHoy());
        cFecha.setText(FechaHoy());
        jCalendario.setVisible(false);
        cFecha.setVisible(false);
        bFecha.setVisible(false);
        jLabel2.setVisible(false);
        AgregarTabla();
        CalcularTotalTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lTituloEncabezado = new javax.swing.JLabel();
        cFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bFecha = new javax.swing.JButton();
        jCalendario = new com.toedter.calendar.JCalendar();
        lFechaRegistro = new javax.swing.JLabel();
        cFechaHoy = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cNombreVenta = new javax.swing.JComboBox<>();
        cTipoVenta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tVentas = new javax.swing.JTable();
        bRegistrar = new javax.swing.JButton();
        lTotal = new javax.swing.JLabel();
        bEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cComentario = new javax.swing.JTextField();
        bPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Ventas");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(156, 195, 219));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTituloEncabezado.setFont(new java.awt.Font("Stencil", 0, 56)); // NOI18N
        lTituloEncabezado.setText("registro de ventas");
        jPanel2.add(lTituloEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 110));
        jPanel1.add(cFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 140, -1));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLabel2.setText("Fecha registro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 140, -1));

        bFecha.setText("jButton1");
        bFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFechaActionPerformed(evt);
            }
        });
        jPanel1.add(bFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 150, 30, -1));

        jCalendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCalendarioMouseEntered(evt);
            }
        });
        jCalendario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jCalendarioPropertyChange(evt);
            }
        });
        jPanel1.add(jCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, -1, -1));

        lFechaRegistro.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lFechaRegistro.setText("Registros de la fecha");
        jPanel1.add(lFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 420, 60));

        cFechaHoy.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        cFechaHoy.setSelected(true);
        cFechaHoy.setText("Fecha de hoy");
        cFechaHoy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cFechaHoyMouseClicked(evt);
            }
        });
        cFechaHoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFechaHoyActionPerformed(evt);
            }
        });
        jPanel1.add(cFechaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, 40));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLabel6.setText("Comentario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 120, -1));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLabel4.setText("Tipo de venta:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 130, -1));

        cNombreVenta.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        cNombreVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cNombreVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cNombreVentaMouseClicked(evt);
            }
        });
        jPanel1.add(cNombreVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 230, 40));

        cTipoVenta.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        cTipoVenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cTipoVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cTipoVentaMouseClicked(evt);
            }
        });
        jPanel1.add(cTipoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, 40));

        tVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tVentasMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 1020, 160));

        bRegistrar.setText("Registrar");
        bRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(bRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, -1, -1));

        lTotal.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        lTotal.setText("Total: $");
        jPanel1.add(lTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 180, 40));

        bEliminar.setText("Eliminar");
        bEliminar.setEnabled(false);
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jLabel7.setText("Nombre de venta:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 180, -1));

        cComentario.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jPanel1.add(cComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 390, 40));

        bPagar.setText("Pagar");
        bPagar.setEnabled(false);
        bPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagarActionPerformed(evt);
            }
        });
        jPanel1.add(bPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if(evt.getKeyCode()== java.awt.event.KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }//GEN-LAST:event_formKeyTyped

    private void bFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFechaActionPerformed
        if(jCalendario.isVisible() == false){
            jCalendario.setVisible(true);
        }else{
            jCalendario.setVisible(false);
        }
    }//GEN-LAST:event_bFechaActionPerformed

    private void jCalendarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCalendarioMouseEntered
        jCalendario.repaint();
    }//GEN-LAST:event_jCalendarioMouseEntered

    private void jCalendarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jCalendarioPropertyChange
        if(evt.getOldValue() != null){
            SimpleDateFormat ff = new SimpleDateFormat("yyyy-MM-dd");
            cFecha.setText(ff.format(jCalendario.getCalendar().getTime()));
            lFechaRegistro.setText("Registrar en "+ff.format(jCalendario.getCalendar().getTime()));
        }
    }//GEN-LAST:event_jCalendarioPropertyChange

    private void cFechaHoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFechaHoyActionPerformed
        MostrarCampoFecha(cFechaHoy.isSelected());
    }//GEN-LAST:event_cFechaHoyActionPerformed

    private void tVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tVentasMouseClicked
        jCalendario.setVisible(false);
        fila = tVentas.rowAtPoint(evt.getPoint());
  

        if (fila >= 0) {
            bEliminar.setEnabled(true);
            String valorFecha = tVentas.getValueAt(fila, 0) != null ? tVentas.getValueAt(fila, 0).toString() : "";
            String valorTipoVenta = tVentas.getValueAt(fila, 1) != null ? tVentas.getValueAt(fila, 1).toString() : "";
            String valorNombreVenta = tVentas.getValueAt(fila, 2) != null ? tVentas.getValueAt(fila, 2).toString() : "";
            String valorComentario = tVentas.getValueAt(fila, 3) != null ? tVentas.getValueAt(fila, 3).toString() : "";

            cFechaHoy.setSelected(false);
            cFecha.setText(valorFecha);
            MostrarCampoFecha(cFechaHoy.isSelected());
            cTipoVenta.setSelectedItem(valorTipoVenta);
            cNombreVenta.setSelectedItem(valorNombreVenta);
        }
    }//GEN-LAST:event_tVentasMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        jCalendario.setVisible(false);
        if(fila >=0){
            cNombreVenta.setSelectedIndex(0);
            cComentario.setText("");
            cFechaHoy.setSelected(true);
            MostrarCampoFecha(cFechaHoy.isSelected());
            bEliminar.setEnabled(false);
            fila = -1;
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void cTipoVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cTipoVentaMouseClicked
        jCalendario.setVisible(false);
    }//GEN-LAST:event_cTipoVentaMouseClicked

    private void cNombreVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cNombreVentaMouseClicked
        jCalendario.setVisible(false);
    }//GEN-LAST:event_cNombreVentaMouseClicked

    private void cFechaHoyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cFechaHoyMouseClicked
        jCalendario.setVisible(false);
    }//GEN-LAST:event_cFechaHoyMouseClicked

    private void bRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarActionPerformed
        AgregarRowsTabla();
    }//GEN-LAST:event_bRegistrarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        EliminarRowsTabla();
        bEliminar.setEnabled(false);
    }//GEN-LAST:event_bEliminarActionPerformed

    private void tVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tVentasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tVentasMouseEntered

    private void bPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagarActionPerformed
        boolean pagado;
        ConfirmacionPago confirmacionPago = new ConfirmacionPago(RegistrarVentas.this, true);
        confirmacionPago.setTotalPagar(CalcularTotalTabla());
        confirmacionPago.setVisible(true);
        pagado = confirmacionPago.pagado;
        if(pagado == true){
            dispose();
        }
    }//GEN-LAST:event_bPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarVentas dialog = new RegistrarVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    int fila = -1;
    String[] titulos={"Fecha","Tipo Venta","Nombre Venta", "Comentario", "Precio"};
    String[] registro = new String[5];
    DefaultTableModel modelo;  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bFecha;
    private javax.swing.JButton bPagar;
    private javax.swing.JButton bRegistrar;
    private javax.swing.JTextField cComentario;
    private javax.swing.JTextField cFecha;
    private javax.swing.JCheckBox cFechaHoy;
    private javax.swing.JComboBox<String> cNombreVenta;
    private javax.swing.JComboBox<String> cTipoVenta;
    private com.toedter.calendar.JCalendar jCalendario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lFechaRegistro;
    private javax.swing.JLabel lTituloEncabezado;
    private javax.swing.JLabel lTotal;
    private javax.swing.JTable tVentas;
    // End of variables declaration//GEN-END:variables
    String FechaHoy(){
        LocalDate fechaHoy = LocalDate.now();
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        return fechaHoy.format(formatoFecha);
    }
    
    void MostrarCampoFecha(Boolean mostrar){
        if(mostrar){
            lFechaRegistro.setText("Registrar en "+FechaHoy());
            cFecha.setVisible(false);
            bFecha.setVisible(false);
            jLabel2.setVisible(false);
        }else{
            lFechaRegistro.setText("Registrar en "+cFecha.getText());
            cFecha.setVisible(true);
            bFecha.setVisible(true);
            jLabel2.setVisible(true);
        }
    }
    
    void AgregarTabla(){      
        modelo = new DefaultTableModel(null, titulos){            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tVentas.setModel(modelo);
    }
    
    void AgregarRowsTabla(){
        if(cFechaHoy.isSelected() == true){
            registro[0] = FechaHoy();
        }else{
            registro[0] = cFecha.getText();
        }
        registro[1] = cTipoVenta.getSelectedItem().toString();
        registro[2] = cNombreVenta.getSelectedItem().toString();
        if(!cComentario.getText().equals("")){
            registro[3] = cComentario.getText();
        }else{
            registro[3] = "Sin comentarios";
        }
        registro[4] = "30";
        modelo.addRow(registro);
        CalcularTotalTabla();
        
        cComentario.setText("");
        ValidaSiHayRegistrosPagar();
    }
    
    int CalcularTotalTabla(){
        int totalRows = modelo.getRowCount(), total = 0;
        
        if(totalRows != 0){
            for(int i = 0; i < totalRows; i++){
                total = total + Integer.parseInt(String.valueOf(modelo.getValueAt(i, 4)));
            }
        }
        lTotal.setText("Total: $"+String.valueOf(total));
        return total;
    }
    
    void EliminarRowsTabla(){
        modelo.removeRow(fila);
        CalcularTotalTabla();
        cNombreVenta.setSelectedIndex(0);
        cComentario.setText("");
        cFechaHoy.setSelected(true);
        MostrarCampoFecha(cFechaHoy.isSelected());
        ValidaSiHayRegistrosPagar();
    }
    
    void ValidaSiHayRegistrosPagar(){
        if(modelo.getRowCount() > 0){
            bPagar.setEnabled(true);
        }else{
            bPagar.setEnabled(false);
        }
    }
          
}

